ALPHAVANTAGE_APIURL = 'https://www.alphavantage.co/query?'

ALPHAVANTAGE_APIKEY_KEY = 'apikey'
ALPHAVANTAGE_APIKEY_VAL = '4F9G7E51ZEMJ6L2B'

ALPHAVANTAGE_FUNC_KEY = 'function'
ALPHAVANTAGE_FUNC_OVERVIEW = 'OVERVIEW'

ALPHAVANTAGE_SYMBOL_KEY = 'symbol'

def get_asset_info_url(symbol, attributes):

  url = ALPHAVANTAGE_APIURL + ALPHAVANTAGE_APIKEY_KEY + '=' + ALPHAVANTAGE_APIKEY_VAL + '&' + ALPHAVANTAGE_FUNC_KEY + '=' + ALPHAVANTAGE_FUNC_OVERVIEW + '&' + ALPHAVANTAGE_SYMBOL_KEY + '=' + symbol

  return url
